[theme]
name = "plain"
[theme.overrides]
separator = " "
separator_bg = "#191c25"

[icons]
name = "none"

[[block]]
block = "focused_window"
format = "{combo}"
max_width = 50
show_marks = "all"
[block.theme_overrides]
idle_bg = "#191c25"
idle_fg = "#cdb6dd"

#[[block]]
#block = "cpu"
#interval = 2
#format = "{utilization}"
#[block.theme_overrides]
#idle_bg = "#191c25"
#idle_fg = "#77adb1"

[[block]]
block = "custom"
command = "/home/mashu/bin/cpuusage"
interval = 2
[block.theme_overrides]
idle_bg = "#191c25"
idle_fg = "#77adb1"

[[block]]
block = "custom"
command = "/home/mashu/bin/memfree"
interval = 2
[block.theme_overrides]
idle_bg = "#191c25"
idle_fg = "#77adb1"

[[block]]
block = "net"
device = "wlan0"
format = "{speed_down;M*b} / {speed_up;M*b}"
interval = 1
[block.theme_overrides]
idle_bg = "#191c25"
idle_fg = "#77adb1"

[[block]]
block = "sound"
on_click = "pavucontrol"
format = "{volume}"
[block.theme_overrides]
idle_bg = "#191c25"
idle_fg = "#94cdd1"

[[block]]
block = "time"
format = "%a %m/%d %H:%M:%S"
interval = 1
locale = "en_GB"
[block.theme_overrides]
idle_bg = "#191c25"
idle_fg = "#889bb4"
