[theme]
theme = "plain"
[theme.overrides]
separator = " "
separator_bg = "#191c25"

[icons]
icons = "none"

[[block]]
block = "focused_window"
format = " $title.str(max_w:100) | "
[block.theme_overrides]
idle_bg = "#191c25"
idle_fg = "#cdb6dd"

#[[block]]
#block = "cpu"
#interval = 2
#format = "{utilization}"
#[block.theme_overrides]
#idle_bg = "#191c25"
#idle_fg = "#77adb1"

#[[block]]
#block = "custom"
#command = "/home/mashu/bin/cpuusage"
#interval = 2
#[block.theme_overrides]
#idle_bg = "#191c25"
#idle_fg = "#77adb1"

[[block]]
block = "custom"
command = "/home/mashu/bin/memfree"
interval = 2
[block.theme_overrides]
idle_bg = "#191c25"
idle_fg = "#77adb1"

[[block]]
block = "temperature"
format = "$average avg, $max max"
chip = "k10temp-pci-00c3"
[block.theme_overrides]
idle_bg = "#191c25"
idle_fg = "#77adb1"
good_bg = "#191c25"
good_fg = "#77adb1"
info_bg = "#191c25"
info_fg = "#77adb1"
warning_bg = "#191c25"
interval = 1

[[block]]
block = "net"
device = "wlan0"
format = " $speed_down.eng(prefix:M)/$speed_up.eng(prefix:M) "
interval = 1
[block.theme_overrides]
idle_bg = "#191c25"
idle_fg = "#77adb1"

[[block]]
block = "sound"
show_volume_when_muted = true
format = " {$volume.eng(w:2)} "
[block.theme_overrides]
idle_bg = "#191c25"
idle_fg = "#94cdd1"

[[block]]
block = "time"
format = " $timestamp.datetime(f:%X) "
interval = 1
[block.theme_overrides]
idle_bg = "#191c25"
idle_fg = "#889bb4"
