# Substrata
[colors]
foreground = "bfbed0"
background = "#191c25"
cursor_bg = "#bfbed0"
cursor_border = "#bfbed0"
cursor_fg = "#191c25"
selection_bg = "#272935"
selection_fg = "#b5b4c9"
scrollbar_thumb = "#272935"
split = "#272935"
ansi = ["#191c25","#a994b8","#77adb1","#c5c4d4","#889bb4","#a994b8","#77adb1","#bfbed0"]
brights = ["#666b7f","#cdb6dd","#94ccd1","#f0ecfe","#afc5de","#cdb6dd","#94ccd1","#f0ecfe"]
